:scheduler:
  :schedule:
    price_discovery:
      every: 30 minutes
      class: PriceDiscovery::CoordinatorWorker
    airdrop:
      cron: '0 0 * * * *'
      class: Airdrop::CoordinatorWorker
    tron:
      every: 30 seconds
      class: Tron::EscrowDeploymentWorker
